[tool.poetry]
name = "service-2"
version = "0.1.0"
description = "Add your description here"
authors = ["John Smith <john@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
